### ISSUE TITLE
Question: How does this work again?

### ISSUE THREAD

**Issue by thatTPR** [seniorjoinu/ic-stable-memory-allocator#1]
I might be confused about the inner workings of ICP but it is my understanding that regardless of subnet allowance a canister can be at most 4gb in size . This would seem to imply that you need to dynamically create new canisters no? Is this done here and I missed it?

**Comment by seniorjoinu** [comment]
Hey there.
No, canisters can be more than 4GB in size, because of stable memory. This memory lives outside canister's heap and you can address it with 64-bit pointers, despite the fact that wasm is a 32-bit environment.
This library introduces a custom stable memory allocator, that enables your dapp to easily use this 64-bit pointers, and uses it in order to implement custom data collections, which can hold as many data, as the subnet would allow it to hold.

A single subnet is limited with 300GB of stable memory. So, if your canister is the only one presenting in a subnet it can take over all these 300GB of memory.

**Comment by seniorjoinu** [comment]
It turns out, that none of us was right. 
Read this thread to know more https://forum.dfinity.org/t/ic-stable-memory-rust-library/14158/19
